FROM ubuntu
RUN apt-get update -y
RUN apt-get install wget -y
RUN wget https://github.com/OrenGitHub/dhscanner/releases/download/v0.0.1/kbgen.elf.aarch64
RUN chmod +x kbgen.elf.aarch64
CMD ["./kbgen.elf.aarch64"]